POST http://localhost:3000/api/orders
Content-Type: application/json
Cookie: session=hG30i0HN_Kjem-uCcU3PvF_mdLB3D0zjdHC2BrkhytE
{
    "items": [
        {
            "product": 1,
            "quantity": 5
        },
        {
            "product": 2,
            "quantity": 3
        }
    ]
}

GET http://localhost:3000/api/orders
Cookie: session=hG30i0HN_Kjem-uCcU3PvF_mdLB3D0zjdHC2BrkhytE

GET http://localhost:3000/api/orders/1
Cookie: session=hG30i0HN_Kjem-uCcU3PvF_mdLB3D0zjdHC2BrkhytE

GET http://localhost:3000/api/orders/1/items
Cookie: session=hG30i0HN_Kjem-uCcU3PvF_mdLB3D0zjdHC2BrkhytE

PUT http://localhost:3000/api/orders/1/cancel
Cookie: session=hG30i0HN_Kjem-uCcU3PvF_mdLB3D0zjdHC2BrkhytE