GET http://localhost:3000/api/products/2
Content-Type: application/json

GET http://localhost:3000/api/products?query=KEYB
Content-Type: application/json

POST http://localhost:3000/api/products
Content-Type: application/json
{
    "productName": "Test Name",
    "description": "Test Description",
    "price": 100,
    "stockAmount": 10,
    "images": [
        "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQyr-fYDvlhIXl1jOYEP8kyPHYqn8e5itRQyoYlxpWhqJN8w8IfXs9ie6JaIzrr8hnoS2C2ehhpmXSkGdCnpEKIPutzVGOfvEFXoW2jw4XTT4RfJ73k-Ngezg",
        "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcS6Z_YTbOqXJEvQmyD1czRFNqDzNwX1eFYcBrj-1NHduoGnlLoMjOx1EYhHmuZhx2IpJQ-OYiGNpneHuzBMyFZJlxPTACl2NOgH9HtcQ9efnr88bdQdCozY"
    ]
}

PATCH http://localhost:3000/api/products/2
Content-Type: application/json
{
    "productName": "Test Name",
    "description": "Test Description",
    "price": 100,
    "stockAmount": 10,
    "images": [
        "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQyr-fYDvlhIXl1jOYEP8kyPHYqn8e5itRQyoYlxpWhqJN8w8IfXs9ie6JaIzrr8hnoS2C2ehhpmXSkGdCnpEKIPutzVGOfvEFXoW2jw4XTT4RfJ73k-Ngezg",
        "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcS6Z_YTbOqXJEvQmyD1czRFNqDzNwX1eFYcBrj-1NHduoGnlLoMjOx1EYhHmuZhx2IpJQ-OYiGNpneHuzBMyFZJlxPTACl2NOgH9HtcQ9efnr88bdQdCozY"
    ]
}

POST http://localhost:3000/api/products/2/ratings
Content-Type: application/json
Cookie: session=llrzbvwfnjTVLK0XNgdqhVm3sBEo8yqcjiYPY1eYOfw
{
    "rating": 3,
    "comment": "Test Comment"
}