GET http://localhost:3000/api/user
Cookie: session=y946V3_45dXa1G-fJcUKdPqP-j9Un3RObPLVFTpbzxU
?? status == 200

# @no-cookie-jar
GET http://localhost:3000/api/user
?? status == 401


GET http://localhost:3000/api/users/2
Cookie: session=y946V3_45dXa1G-fJcUKdPqP-j9Un3RObPLVFTpbzxU
?? status == 200


GET http://localhost:3000/api/users/2
Cookie: session=J4m3e7TZRZeaq4ZF2RB2N8_Q4v2L9D7wpIAbBcz242g
?? status == 403

DELETE http://localhost:3000/api/users/2
Cookie: session=y946V3_45dXa1G-fJcUKdPqP-j9Un3RObPLVFTpbzxU
?? status == 200